//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonBookingApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalonBookingApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info.
        /// </summary>
        public static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountPageTitle {
            get {
                return ResourceManager.GetString("AccountPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created successfully!.
        /// </summary>
        public static string AccountSaved {
            get {
                return ResourceManager.GetString("AccountSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the administrator can view this list!.
        /// </summary>
        public static string AdminOnlyError {
            get {
                return ResourceManager.GetString("AdminOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Clients.
        /// </summary>
        public static string AllClientsHeader {
            get {
                return ResourceManager.GetString("AllClientsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment created successfully!.
        /// </summary>
        public static string AppointmentSaved {
            get {
                return ResourceManager.GetString("AppointmentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string AppointmentTitle {
            get {
                return ResourceManager.GetString("AppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string AppointsTab {
            get {
                return ResourceManager.GetString("AppointsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Refresh - Ideal for the essentials.
        /// </summary>
        public static string BasicConcept {
            get {
                return ResourceManager.GetString("BasicConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 1 x Roots Retouch\n• 1 x Classic Manicure .
        /// </summary>
        public static string BasicInclusions {
            get {
                return ResourceManager.GetString("BasicInclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 5% off any other extra service.
        /// </summary>
        public static string BasicPerks {
            get {
                return ResourceManager.GetString("BasicPerks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Appointment.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + New Appointment.
        /// </summary>
        public static string BtnNewAppoint {
            get {
                return ResourceManager.GetString("BtnNewAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BtnNo {
            get {
                return ResourceManager.GetString("BtnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string BtnSaveChanges {
            get {
                return ResourceManager.GetString("BtnSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string BtnUsePackage {
            get {
                return ResourceManager.GetString("BtnUsePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BtnYes {
            get {
                return ResourceManager.GetString("BtnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Package.
        /// </summary>
        public static string BuyPackageBtn {
            get {
                return ResourceManager.GetString("BuyPackageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit how much in advance clients can cancel their appointment..
        /// </summary>
        public static string CancelLimitDesc {
            get {
                return ResourceManager.GetString("CancelLimitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Limit.
        /// </summary>
        public static string CancelLimitTitle {
            get {
                return ResourceManager.GetString("CancelLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel? This action cannot be undone..
        /// </summary>
        public static string CancelSubConfirmMsg {
            get {
                return ResourceManager.GetString("CancelSubConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package cancelled successfully..
        /// </summary>
        public static string CancelSubSuccess {
            get {
                return ResourceManager.GetString("CancelSubSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facials.
        /// </summary>
        public static string CatFacial {
            get {
                return ResourceManager.GetString("CatFacial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Style.
        /// </summary>
        public static string CatHair {
            get {
                return ResourceManager.GetString("CatHair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makeup.
        /// </summary>
        public static string CatMakeup {
            get {
                return ResourceManager.GetString("CatMakeup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nail Art.
        /// </summary>
        public static string CatNails {
            get {
                return ResourceManager.GetString("CatNails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CatTitle {
            get {
                return ResourceManager.GetString("CatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Photo.
        /// </summary>
        public static string ChangePhoto {
            get {
                return ResourceManager.GetString("ChangePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose month.
        /// </summary>
        public static string ChooseMonthTitle {
            get {
                return ResourceManager.GetString("ChooseMonthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the perfect plan for you..
        /// </summary>
        public static string ChoosePerfectPlan {
            get {
                return ResourceManager.GetString("ChoosePerfectPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this plan.
        /// </summary>
        public static string ChooseSubscriptionBtn {
            get {
                return ResourceManager.GetString("ChooseSubscriptionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your treat today!.
        /// </summary>
        public static string ChooseTreat {
            get {
                return ResourceManager.GetString("ChooseTreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Details.
        /// </summary>
        public static string ClientDetailsTitle {
            get {
                return ResourceManager.GetString("ClientDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Reviews.
        /// </summary>
        public static string ClientReviews {
            get {
                return ResourceManager.GetString("ClientReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string ClientsTab {
            get {
                return ResourceManager.GetString("ClientsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string ClientTitle {
            get {
                return ResourceManager.GetString("ClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm appointment.
        /// </summary>
        public static string ConfirmAppointBtn {
            get {
                return ResourceManager.GetString("ConfirmAppointBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel?.
        /// </summary>
        public static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm subscription.
        /// </summary>
        public static string ConfirmSubBtn {
            get {
                return ResourceManager.GetString("ConfirmSubBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Services.
        /// </summary>
        public static string CustomizeServices {
            get {
                return ResourceManager.GetString("CustomizeServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP All-Inclusive - The ultimate experience &amp; royal treatment.
        /// </summary>
        public static string DiamondConcept {
            get {
                return ResourceManager.GetString("DiamondConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 1 x Premium Hair Service (Balayage, Ombre, Color+Cut)\n• 1 x Facial Treatment\n• 2 x Manicure/Pedicure\n• 1 x Evening/Event Makeup.
        /// </summary>
        public static string DiamondInclusions {
            get {
                return ResourceManager.GetString("DiamondInclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 20% off products\n• Free drinks (Prosecco/Coffee)\n• &apos;Bring a friend&apos;: 1x/quarter free manicure for a friend.
        /// </summary>
        public static string DiamondPerks {
            get {
                return ResourceManager.GetString("DiamondPerks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover our packages.
        /// </summary>
        public static string DiscoverPackages {
            get {
                return ResourceManager.GetString("DiscoverPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string EmailFormatError {
            get {
                return ResourceManager.GetString("EmailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and Email cannot be empty!.
        /// </summary>
        public static string ErrorEmptyFields {
            get {
                return ResourceManager.GetString("ErrorEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires on:.
        /// </summary>
        public static string ExpiresOn {
            get {
                return ResourceManager.GetString("ExpiresOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra perks:.
        /// </summary>
        public static string ExtraPerks {
            get {
                return ResourceManager.GetString("ExtraPerks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all fields.
        /// </summary>
        public static string FieldsRequired {
            get {
                return ResourceManager.GetString("FieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password?.
        /// </summary>
        public static string ForgotPass {
            get {
                return ResourceManager.GetString("ForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAL SETTINGS.
        /// </summary>
        public static string GeneralSettingsTitle {
            get {
                return ResourceManager.GetString("GeneralSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pampering - Everything in one place.
        /// </summary>
        public static string GoldConcept {
            get {
                return ResourceManager.GetString("GoldConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 1 x Classic Hair Coloring OR 1 x Facial Treatment\n• 2 x Manicure/Pedicure\n• 2 x HairStyling.
        /// </summary>
        public static string GoldInclusions {
            get {
                return ResourceManager.GetString("GoldInclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 15% off any extra service\n• Priority booking\n• A specialty coffee on the house.
        /// </summary>
        public static string GoldPerks {
            get {
                return ResourceManager.GetString("GoldPerks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,.
        /// </summary>
        public static string HiLabel {
            get {
                return ResourceManager.GetString("HiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Appointments.
        /// </summary>
        public static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeTab {
            get {
                return ResourceManager.GetString("HomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included services.
        /// </summary>
        public static string IncludedServices {
            get {
                return ResourceManager.GetString("IncludedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials. No account?.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        public static string LabelAfternoon {
            get {
                return ResourceManager.GetString("LabelAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Services.
        /// </summary>
        public static string LabelAssignServices {
            get {
                return ResourceManager.GetString("LabelAssignServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Service.
        /// </summary>
        public static string LabelChooseService {
            get {
                return ResourceManager.GetString("LabelChooseService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Stylist.
        /// </summary>
        public static string LabelChooseStylist {
            get {
                return ResourceManager.GetString("LabelChooseStylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client: .
        /// </summary>
        public static string LabelClient {
            get {
                return ResourceManager.GetString("LabelClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (min).
        /// </summary>
        public static string LabelDuration {
            get {
                return ResourceManager.GetString("LabelDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        public static string LabelMorning {
            get {
                return ResourceManager.GetString("LabelMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: .
        /// </summary>
        public static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service: .
        /// </summary>
        public static string LabelService {
            get {
                return ResourceManager.GetString("LabelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylist: .
        /// </summary>
        public static string LabelStylist {
            get {
                return ResourceManager.GetString("LabelStylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string LangRomanian {
            get {
                return ResourceManager.GetString("LangRomanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a review.
        /// </summary>
        public static string LeaveReviewBtn {
            get {
                return ResourceManager.GetString("LeaveReviewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogoutBtn {
            get {
                return ResourceManager.GetString("LogoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARKETING &amp; COMMUNICATION.
        /// </summary>
        public static string MarketingCommunication {
            get {
                return ResourceManager.GetString("MarketingCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the maximum number of active bookings a single client can hold..
        /// </summary>
        public static string MaxBookingsDesc {
            get {
                return ResourceManager.GetString("MaxBookingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance bookings per client.
        /// </summary>
        public static string MaxBookingsTitle {
            get {
                return ResourceManager.GetString("MaxBookingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memberships.
        /// </summary>
        public static string MembershipsPageTitle {
            get {
                return ResourceManager.GetString("MembershipsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memberships.
        /// </summary>
        public static string MembershipsTitle {
            get {
                return ResourceManager.GetString("MembershipsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Active Packages.
        /// </summary>
        public static string MyActivePackages {
            get {
                return ResourceManager.GetString("MyActivePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no appointments today..
        /// </summary>
        public static string NoAppointmentsToday {
            get {
                return ResourceManager.GetString("NoAppointmentsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoBtn {
            get {
                return ResourceManager.GetString("NoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stylist has no reviews yet. Be the first!.
        /// </summary>
        public static string NoReviewsMsg {
            get {
                return ResourceManager.GetString("NoReviewsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkBtn {
            get {
                return ResourceManager.GetString("OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One session will be deducted from your active package..
        /// </summary>
        public static string PackageAppliedDesc {
            get {
                return ResourceManager.GetString("PackageAppliedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package applied.
        /// </summary>
        public static string PackageAppliedTitle {
            get {
                return ResourceManager.GetString("PackageAppliedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chose to use the {0} package. Do you want to book an appointment?.
        /// </summary>
        public static string PackageSelectedMessage {
            get {
                return ResourceManager.GetString("PackageSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package selected.
        /// </summary>
        public static string PackageSelectedTitle {
            get {
                return ResourceManager.GetString("PackageSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes:\n• 3 x HairStyling\n• 3 x Evening Makeup\nValidity: 1 Year..
        /// </summary>
        public static string PackEventDesc {
            get {
                return ResourceManager.GetString("PackEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string PackEventName {
            get {
                return ResourceManager.GetString("PackEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes:\n• 3 x Roots Retouch\n• 3 x Women&apos;s Haircut\nValidity: 1 Year..
        /// </summary>
        public static string PackHairDesc {
            get {
                return ResourceManager.GetString("PackHairDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Renewal .
        /// </summary>
        public static string PackHairName {
            get {
                return ResourceManager.GetString("PackHairName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes:\n• 3 x Manicure\n• 3 x Pedicure\nValidity: 1 Year..
        /// </summary>
        public static string PackNailsDesc {
            get {
                return ResourceManager.GetString("PackNailsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect Nails .
        /// </summary>
        public static string PackNailsName {
            get {
                return ResourceManager.GetString("PackNailsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        public static string PassLengthError {
            get {
                return ResourceManager.GetString("PassLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PassPlaceholder {
            get {
                return ResourceManager.GetString("PassPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay at the salon in cash or by card..
        /// </summary>
        public static string PaymentLocationDesc {
            get {
                return ResourceManager.GetString("PaymentLocationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment on location.
        /// </summary>
        public static string PaymentLocationTitle {
            get {
                return ResourceManager.GetString("PaymentLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be 10 digits (07xxxxxxxx)..
        /// </summary>
        public static string PhoneFormatError {
            get {
                return ResourceManager.GetString("PhoneFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhonePlaceholder {
            get {
                return ResourceManager.GetString("PhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Library.
        /// </summary>
        public static string PhotoLibrary {
            get {
                return ResourceManager.GetString("PhotoLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Memberships.
        /// </summary>
        public static string PremiumMemberships {
            get {
                return ResourceManager.GetString("PremiumMemberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Settings.
        /// </summary>
        public static string ProfileAppSettings {
            get {
                return ResourceManager.GetString("ProfileAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Details.
        /// </summary>
        public static string ProfileDetails {
            get {
                return ResourceManager.GetString("ProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Reviews.
        /// </summary>
        public static string ProfileReviews {
            get {
                return ResourceManager.GetString("ProfileReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        public static string ProfileViewProfile {
            get {
                return ResourceManager.GetString("ProfileViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        public static string ProfileWorkingHours {
            get {
                return ResourceManager.GetString("ProfileWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Photo.
        /// </summary>
        public static string RemovePhoto {
            get {
                return ResourceManager.GetString("RemovePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string ReviewsTitle {
            get {
                return ResourceManager.GetString("ReviewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review and confirm.
        /// </summary>
        public static string ReviewTitle {
            get {
                return ResourceManager.GetString("ReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the salon is closed on Sundays..
        /// </summary>
        public static string SalonClosedMessage {
            get {
                return ResourceManager.GetString("SalonClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Salon is closed on Sundays. Moved to the next working day..
        /// </summary>
        public static string SalonClosedMovedMessage {
            get {
                return ResourceManager.GetString("SalonClosedMovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit how soon before the desired time a client can book..
        /// </summary>
        public static string SameDayLimitDesc {
            get {
                return ResourceManager.GetString("SameDayLimitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Day Booking Limit.
        /// </summary>
        public static string SameDayLimitTitle {
            get {
                return ResourceManager.GetString("SameDayLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a service, a stylist, and a time slot..
        /// </summary>
        public static string SelectAllError {
            get {
                return ResourceManager.GetString("SelectAllError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Rating.
        /// </summary>
        public static string SelectRatingTitle {
            get {
                return ResourceManager.GetString("SelectRatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service.
        /// </summary>
        public static string SelectServicePlaceholder {
            get {
                return ResourceManager.GetString("SelectServicePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string ServiceDetailsTitle {
            get {
                return ResourceManager.GetString("ServiceDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyebrow Styling.
        /// </summary>
        public static string ServiceEyebrows {
            get {
                return ResourceManager.GetString("ServiceEyebrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facial Treatments.
        /// </summary>
        public static string ServiceFacials {
            get {
                return ResourceManager.GetString("ServiceFacials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Hair Coloring or Facial Treatments.
        /// </summary>
        public static string ServiceHairorFacial {
            get {
                return ResourceManager.GetString("ServiceHairorFacial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HairStyling .
        /// </summary>
        public static string ServiceHairstyle {
            get {
                return ResourceManager.GetString("ServiceHairstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening Make-up.
        /// </summary>
        public static string ServiceMakeup {
            get {
                return ResourceManager.GetString("ServiceMakeup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manicure.
        /// </summary>
        public static string ServiceManicure {
            get {
                return ResourceManager.GetString("ServiceManicure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manicure/ Pedicure.
        /// </summary>
        public static string ServiceManiPedi {
            get {
                return ResourceManager.GetString("ServiceManiPedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gel Constrcution or Manicure.
        /// </summary>
        public static string ServiceNails {
            get {
                return ResourceManager.GetString("ServiceNails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balayage / Ombre /  Hair Coloring+ Haircut.
        /// </summary>
        public static string ServicePremiumHair {
            get {
                return ResourceManager.GetString("ServicePremiumHair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Touch-up.
        /// </summary>
        public static string ServiceRoots {
            get {
                return ResourceManager.GetString("ServiceRoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Settings.
        /// </summary>
        public static string SettingsAppointmentTitle {
            get {
                return ResourceManager.GetString("SettingsAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to sign out?.
        /// </summary>
        public static string SignOutConfirmation {
            get {
                return ResourceManager.GetString("SignOutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-up.
        /// </summary>
        public static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant Glow - For an always flawless look.
        /// </summary>
        public static string SilverConcept {
            get {
                return ResourceManager.GetString("SilverConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 1 x Gel Construction / Manicure \n• 1 x HairStyling\n• 1 x Eyebrow Styling.
        /// </summary>
        public static string SilverInclusions {
            get {
                return ResourceManager.GetString("SilverInclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 10% off coloring/balayage \n• A specialty coffee on the house.
        /// </summary>
        public static string SilverPerks {
            get {
                return ResourceManager.GetString("SilverPerks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string SpecialtyPlaceholder {
            get {
                return ResourceManager.GetString("SpecialtyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Specialists.
        /// </summary>
        public static string SpecTitle {
            get {
                return ResourceManager.GetString("SpecTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Start!.
        /// </summary>
        public static string StartBtn {
            get {
                return ResourceManager.GetString("StartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylist Details.
        /// </summary>
        public static string StylistDetailsTitle {
            get {
                return ResourceManager.GetString("StylistDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylists.
        /// </summary>
        public static string StylistsTab {
            get {
                return ResourceManager.GetString("StylistsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t work on this day. Please select another one..
        /// </summary>
        public static string StylistUnavailableMessage {
            get {
                return ResourceManager.GetString("StylistUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is off today. Selection moved to the next available day..
        /// </summary>
        public static string StylistUnavailableMovedMessage {
            get {
                return ResourceManager.GetString("StylistUnavailableMovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription added!.
        /// </summary>
        public static string SubAddedSuccess {
            get {
                return ResourceManager.GetString("SubAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Review.
        /// </summary>
        public static string SubmitReviewBtn {
            get {
                return ResourceManager.GetString("SubmitReviewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is made upon the first use of the subscription..
        /// </summary>
        public static string SubPaymentNote {
            get {
                return ResourceManager.GetString("SubPaymentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have purchased the {0} plan. You will be able to see it soon in the My Appointments section..
        /// </summary>
        public static string SuccessBuyMonthly {
            get {
                return ResourceManager.GetString("SuccessBuyMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have purchased the {0} package. You will be able to access it from the My Appointments section..
        /// </summary>
        public static string SuccessBuySession {
            get {
                return ResourceManager.GetString("SuccessBuySession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account details updated!.
        /// </summary>
        public static string SuccessUpdate {
            get {
                return ResourceManager.GetString("SuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string TabCalendar {
            get {
                return ResourceManager.GetString("TabCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Plans.
        /// </summary>
        public static string TabMonthly {
            get {
                return ResourceManager.GetString("TabMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string TabProfile {
            get {
                return ResourceManager.GetString("TabProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Packages.
        /// </summary>
        public static string TabSessions {
            get {
                return ResourceManager.GetString("TabSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total to pay.
        /// </summary>
        public static string TotalPayTitle {
            get {
                return ResourceManager.GetString("TotalPayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Appointments.
        /// </summary>
        public static string UpcomingAppointments {
            get {
                return ResourceManager.GetString("UpcomingAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserPlaceholder {
            get {
                return ResourceManager.GetString("UserPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look Awesome &amp; Save Some.
        /// </summary>
        public static string Welcomemsg {
            get {
                return ResourceManager.GetString("Welcomemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step into a world of personalized services..
        /// </summary>
        public static string WelcomeSub {
            get {
                return ResourceManager.GetString("WelcomeSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s included:.
        /// </summary>
        public static string WhatsIncluded {
            get {
                return ResourceManager.GetString("WhatsIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write about your experience....
        /// </summary>
        public static string WriteReviewPlaceholder {
            get {
                return ResourceManager.GetString("WriteReviewPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesBtn {
            get {
                return ResourceManager.GetString("YesBtn", resourceCulture);
            }
        }
    }
}
